baseURL = 'https://globalazurewarsaw.net/'
languageCode = 'pl-pl'
title = 'Global Azure Warsaw'

[[module.imports]]
    path = "github.com/willfaught/paige"

[paige.analytics]
    disable = false

[paige]
    color = "#0063af"

[[languages.en.menu.main]]
    identifier = "home"
    name = "Global Azure 2023 Warsaw Edition"
    url = "/"
    weight = 10

[[languages.en.menu.main]]
    identifier = "speakers"
    name = "Prelegenci"
    url = "/speakers"
    weight = 20

[[languages.en.menu.main]]
    identifier = "speeches"
    name = "Sesje"
    url = "/speeches"
    weight = 30

[[languages.en.menu.main]]
    identifier = "agenda"
    name = "Agenda"
    url = "/agenda"
    weight = 40